before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
    - VERSION={{ if .Branch == "develop" }} {{ .Version }} {{ else }} {{ .Branch }} {{ end }}
  binary: '{{ .ProjectName }}_v{{ .Version }}'
  ldflags: -X github.com/scalr/terraform-provider-scalr/version.ProviderVersion={{ .Env.VERSION }}

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "devel"
