before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: '{{ .ProjectName }}_v{{ .Version }}'

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "devel"
