before:
  hooks:
    - go mod download
builds:
- env:
    CGO_ENABLED: 0
    VERSION: '{{ if .Branch == "develop" }} {{ .Version }} {{ else }} {{ .Branch }} {{ end }}'
  ldflags: '-s -w -X "github.com/scalr/terraform-provider-scalr/version.ProviderVersion={{ .Env.VERSION }}"'
  binary: '{{ .ProjectName }}_v{{ .Version }}'

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "devel"
