before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  ldflags:
    - '-X github.com/scalr/terraform-provider-scalr/version.ProviderVersion={{ .Version }}'
    - '-X github.com/scalr/terraform-provider-scalr/version.Branch={{ .Branch }}'
  binary: '{{ .ProjectName }}_v{{ .Version }}'

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "devel"
