name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go 1.11.4
        uses: actions/setup-go@v2
        with:
          go-version: "1.11.4"
      - name: fmt
        run: test -z $(gofmt -l .)
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up go 1.11.4
        uses: actions/setup-go@v2
        with:
          go-version: "1.11.4"

      - name: unit tests
        run: make test
