name: default

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"

      - name: Run unit tests
        run: make test
  acc-tests:
    runs-on: ubuntu-latest
    name: acc-tests
    env:
      REVIZOR_URL: ${{ secrets.REVIZOR_URL }}
      REVIZOR_TOKEN: ${{ secrets.REVIZOR_TOKEN }}
      SCALR_TOKEN: ${{ secrets.SCALR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: Environment settings
        env:
          API_BRANCH: ${{ contains(github.event.head_commit.message, '[API_BRANCH]') }}
          DB_BRANCH: ${{ contains(github.event.head_commit.message, '[DB_BRANCH]') }}
        run: |
          echo "API_BRANCH=${API_BRANCH}" >> $GITHUB_ENV
          echo "Set env variable from commit message: API_BRANCH=${API_BRANCH}"
          echo "DB_BRANCH=${DB_BRANCH}" >> $GITHUB_ENV
          echo "Set env variable from commit message: DB_BRANCH=${DB_BRANCH}"
          echo BRANCH=${GITHUB_REF#refs/heads/} >> $GITHUB_ENV
          echo "Set env variable: BRANCH=${GITHUB_REF#refs/heads/}"
      - name: Create container
        id: create
        uses: Scalr/gh-action-revizor@master
        with:
          command: create
      - name: Run acceptance tests
        env:
          SCALR_HOSTNAME: ${{ steps.create.outputs.hostname }}
        run: make testacc
      - name: Delete container
        id: delete
        if: ${{ always() && steps.create.outputs.container_id }}
        uses: Scalr/gh-action-revizor@master
        with:
          command: delete
          container_id: ${{ steps.create.outputs.container_id }}
  release:
    name: release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [lint, unit-tests, acc-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.13"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
